/**
 * Date formatting and calculation utilities.
 */

/**
 * Get a consistent date key string (YYYY-MM-DD) for storage lookups.
 * @param {Date} date
 * @returns {string}
 */
export const getDateKey = (date) => {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
};

/**
 * Get a month key string (YYYY-MM) for grouping.
 * @param {Date} date
 * @returns {string}
 */
export const getMonthKey = (date) => {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  return `${y}-${m}`;
};

/**
 * Returns the number of days in a given month/year.
 */
export const getDaysInMonth = (year, month) => {
  return new Date(year, month + 1, 0).getDate();
};

/**
 * Returns the day-of-week (0=Sun) for the 1st of the month.
 */
export const getFirstDayOfMonth = (year, month) => {
  return new Date(year, month, 1).getDay();
};

/**
 * Format a number as Indian Rupees.
 */
export const formatCurrency = (amount) => {
  return `₹${Number(amount).toFixed(2)}`;
};

/**
 * Format date for display (e.g., "15 Jan 2026").
 */
export const formatDisplayDate = (dateKey) => {
  const date = new Date(dateKey + 'T00:00:00');
  const months = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ];
  return `${date.getDate()} ${months[date.getMonth()]} ${date.getFullYear()}`;
};

/**
 * Get the full month name and year (e.g., "February 2026").
 */
export const getMonthYearLabel = (year, month) => {
  const months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];
  return `${months[month]} ${year}`;
};

/**
 * Build a shareable text summary for the month.
 */
export const buildShareText = (monthLabel, entries, payments, totalLiters, totalDue, totalPaid, pricePerLiter) => {
  let text = `🥛 *Milk Summary — ${monthLabel}*\n`;
  text += `━━━━━━━━━━━━━━━━━━━━\n\n`;
  text += `📊 *Overview*\n`;
  text += `  Total Milk: ${totalLiters.toFixed(1)} liters\n`;
  text += `  Rate: ${formatCurrency(pricePerLiter)}/liter\n`;
  text += `  Total Bill: ${formatCurrency(totalLiters * pricePerLiter)}\n`;
  text += `  Paid: ${formatCurrency(totalPaid)}\n`;
  text += `  *Balance Due: ${formatCurrency(totalDue)}*\n\n`;

  // Daily breakdown
  const sortedKeys = Object.keys(entries).sort();
  if (sortedKeys.length > 0) {
    text += `📅 *Daily Log*\n`;
    sortedKeys.forEach((key) => {
      const e = entries[key];
      if (e.liters > 0) {
        text += `  ${formatDisplayDate(key)}: ${e.liters}L`;
        if (e.note) text += ` — "${e.note}"`;
        text += `\n`;
      }
    });
    text += `\n`;
  }

  // Payments
  if (payments.length > 0) {
    text += `💰 *Payments*\n`;
    payments.forEach((p) => {
      text += `  ${formatDisplayDate(p.date)}: ${formatCurrency(p.amount)}`;
      if (p.note) text += ` — "${p.note}"`;
      text += `\n`;
    });
  }

  text += `\n━━━━━━━━━━━━━━━━━━━━\n`;
  text += `Generated by Milk Tracker 🥛`;
  return text;
};